
// create json file with planet data

const PlanetInfo = {
    sun: {
        name: "Sun",
        radius: 4,
        texture: "/textures/planets/sun.jpg",
        position: [0, 0, 0],
        isBloomLayer: true,
        color: 0xffff00,
    },
    mercury: {
        name: "Mercury",
        radius: 0.07 / 2,
        texture: "/textures/planets/mercury.jpg",
        position: [11.28, 0, 0],
        isBloomLayer: false,
        color: 0xaaaaaa,
        distance: 11.28,
        timeMultiplier: 4.14,
        rotationMultiplier: 0.017,
    },
    venus: {
        name: "Venus",
        radius: 0.17 / 2,
        texture: "/textures/planets/venus_surface.jpg",
        position: [12.45, 0, 0],
        isBloomLayer: false,
        color: 0xffcc00,
        distance: 12.45,
        timeMultiplier: 1.61,
        rotationMultiplier: -0.004,
    },
    earth: {
        name: "Earth",
        radius: 0.18 / 2,
        texture: "/textures/planets/earth.jpg",
        position: [13.38, 0, 0],
        isBloomLayer: false,
        color: 0x2233ff,
        distance: 13.38,
        timeMultiplier: 1.00,
        rotationMultiplier: 1.00,
    },
    mars: {
        name: "Mars",
        radius: 0.10 / 2,
        texture: "/textures/planets/mars.jpg",
        position: [15.04, 0, 0],
        isBloomLayer: false,
        color: 0xff5500,
        distance: 15.04,
        timeMultiplier: 0.72,
        rotationMultiplier: 0.97,
    },
    jupiter: {
        name: "Jupiter",
        radius: 2.01 / 2,
        texture: "/textures/planets/jupiter.jpg",
        position: [28.51, 0, 0],
        isBloomLayer: false,
        color: 0xff9900,
        distance: 28.51,
        timeMultiplier: 0.30,
        rotationMultiplier: 2.44,
    },
    saturn: {
        name: "Saturn",
        radius: 1.67 / 2,
        texture: "/textures/planets/saturn.jpg",
        position: [43.24, 0, 0],
        isBloomLayer: false,
        color: 0xffdd99,
        distance: 43.24,
        ringTexture: "/textures/planets/saturn_ring_alpha.png",
        timeMultiplier: 0.18,
        rotationMultiplier: 2.22,
    },
    uranus: {
        name: "Uranus",
        radius: 0.73 / 2,
        texture: "/textures/planets/uranus.jpg",
        position: [75.12, 0, 0],
        isBloomLayer: false,
        color: 0x66ccff,
        distance: 75.12,
        timeMultiplier: 0.09,
        rotationMultiplier: -1.39,
    },
    neptune: {
        name: "Neptune",
        radius: 0.71 / 2,
        texture: "/textures/planets/neptune.jpg",
        position: [110.36, 0, 0],
        isBloomLayer: false,
        color: 0x3366ff,
        distance: 110.36,
        timeMultiplier: 0.06,
        rotationMultiplier: 1.49,
    }
}

export { PlanetInfo };